---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret-key
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_SECRET_KEY: AgBRakkL5PBsm3nqhpRE2aMW9iET3HlSLcR/kquWIG243C2dTRNUbO3/GgNWgARm7VRJ6XywjWERTmScGqNbfMtqtAF2tRmhAoLGu7J8q0Xi9LFnLeB1kN6ffy0bs7Ea4ttLhiBfcJd9suV4YktghUEwKI9/gbsPc3b3C7/ek0Wi+Lc5hwynQ2HvaphZYFODtHKPYEDIpihYNT6N6v7o/RqTyE0IDYcXbsY9DBFTJtmWizSmqRAb8L2TFUQi/4jXlVmORTxTIQ3Kv8DbwvDb0ZvWBBc3Ch1bi5rLMRCzo2H+5KNeAs0R6IwF/mBq9cU3x2HMtTBbviq3QXAGg8mF0oE0FAab7+vtjcyMefOyHa1AJVficTffPDjwYVODk4vlFTK4unDhnJrtvXlezrcG26AoDm3Mjq5LvuHPMFMmBLePsAf6SPKZ2s528Db+TazLGFKrebo6OrgImIU7hcpNb25XrJodQzGFo1tm6BP+uztzJ2Ny0DMWRLyYHnmXFdjTqj4VOOOYg6YSC6kJa2PPOb/D2FvQNYhkFovGKNxeTPTTCXyecS7hTymuDE+zmYdhEOuptJQsWxapMdTpx7RUqu4Gv5L+vMjlPgQHTv0ysdEsaVfsXzH0L8aoWnpJc8Vem++ENyG+nnNZsCuwsR2us65giLT6BbUmU8lBMhlNYsyQEmRpRA0w06x8BMOjmBk+a+H/6ioB200Reo9KkZ0PuZNS9PjeXYQhdiSBnbefR17nkbftKiDy5hkdBgM89FXB9oPL79o4+oE8P8UPmO4Ukwi+
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret-key
      namespace: authentik
    type: Opaque
