apiVersion: v2
name: authentik
version: 0.0.0
dependencies:
  - name: authentik
    version: 2025.6.1
    repository: https://charts.goauthentik.io
  - name: cluster
    alias: cloudnative-pg
    version: 0.3.1
    repository: https://cloudnative-pg.github.io/charts
  - name: redis-replication
    version: 0.16.7
    repository: https://ot-container-kit.github.io/helm-charts
