apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: authentik
  namespace: argo-cd
spec:
  destinations:
  - name: in-cluster
    namespace: authentik
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
  sourceRepos:
  - https://github.com/ai-platform-infrastructure/open-webui-k8s.git # git repository
