apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kuberay-operator
spec:
  destinations:
  - name: in-cluster
    namespace: kuberay-operator
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: admissionregistration.k8s.io
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
  sourceRepos:
  - https://github.com/ai-platform-infrastructure/open-webui-k8s.git # git repository
