---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-s3-backup-credentials
  namespace: litellm
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCmGMATRSfWhUdF/SBS+dkSafJB/UWJZ4kF4vIyUVRgVCM2NJZNeys1hQ8kPJDGyYoOavh6UpQR4rvV8bHkczzp2ykDlbOiPCSwxDRw/0XxlwgxMdYxeDH40WpyvxJBMBQawmgtHgtA8QNSsuIk9ofUkI1lJETd+zKaUVv6lEK5KsrxgaWyy5V3kP89KVUR6suStz0ERl/VNI3Da7ZBD9iOZH6+uyDaUZZqsjC50MomDSGfL5g/JF0q4Hzb0mxWreE0S313BbJvvnBclW5I583QklvvEjTkFFSkwYXmGbk41UH6SXAYisaUHGSl2iPMyR9Ivjxk+tvQ2zTEUlB8PJv6FEa8CyLVStYcKQlYhibu1g0ntel1DFZSBBngNwvsPhufhWb3/Kw3o88MzHyz9WxaX28/pyCCJxRGzOZ94jxh2rYnRLa23zsPQthfVfhfFfo/iC3/313tOh36EjLmS6Cv96lxgcr8582B9jBUTC4gGGG7ZOSQl14FOa0WOw8TuK9HZRaCJGU7NUDG/F4gMK2WsJDs1oCb9A7dj7jweI+VdLFKqqmNIJYf2PrkPbS07xV3eJJC7SxlpvnHgMg0wXeQ+iWoO+fTizmAhESSj4Ok4DPpERY1lBL316s/wVGYDW9/XtnMtvG4twu2+WmlTBNxJw0w3MNhvyxwr8ovxTj9xm8mFqiKZ9PQW//e10NmyE6sRf4dZB7pvx5ckaJf5QWfT1jCLQ==
    ACCESS_SECRET_KEY: AgBx+ZWnXJTVblpX9aDJlR6ZsIDU5N3LbiLBoUl2W2q8Sp0N57vzyi4/d/DsEIIfJL013ASDTLYE0VHeLVv+kmwifyAMYRSfxkm47k7Pn7Ie+mbP7ogTesJa5QMtKqKKwGgWSskyoaeV3nLKfKuk3tsBa/jpALKOVWh95wlPs1zLyE9xkLjbMxnf2om1RWq2TU57RzhPKTR1ErUpiD2OADowk1bHoqNKBPrnG7ZqAKqm7Xvgwd86eAr01f6bwtq/csgQQZ5YYCIlhdaL6PkIGib1KwQhuHL1XT5+fIjiZCxBjQC28isZJCz5R9UnmPTP+sFRYuk3napSLiujs4YNJT6u5Nq0g3uFZvMAio02EMa8AmMovwqjAmigEu9fhGfViRI6uFAexRHzobPASaQos6RbWshXV3XhPJ/vnFpyJt07JxrrcH8GCDdVFPDdgjRu3zaS7waTECPD7+JOWsOv7I6nvR0+IymJWec7D2S0RYZDKLDCTWJYFg2ikx8I3P/WoqybpKTBjefoFijClWtix3pqTyF4ewOBwyfEs5lsPjDW1pGlVQxA2my/wtjxQzruggEhFf8XUUzbGxzRex4+7AWhiIEdq1cR5NGH0wkHJHhnB+tkz8YNcb3SmVud10eAKI3ICHBBl4/sN1AsBmqmuhDywz8jQCAlWsTh9PvSDJqoZBVqYcmJ5Nm2NlbNM7chLwMn3PFfVzbf6yyMZVV0i2JA2MGQd2g8X0E450oczP3j6LSxSlYO1DOr
  template:
    metadata:
      creationTimestamp: null
      name: hetzner-s3-backup-credentials
      namespace: litellm
    type: Opaque
