---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgBEhFjUJabZYxYQE1AH+lMqxvrvkTWwKAVc7vfgEVpdO/II7QnSq+l5q7nCv5XGx7jSkLyJMt2O4owhMRVoRwUOUJBRbFBHHP65NHszOUQaJGVImlSv7ldARIX+GQldmCVBe1EGfHWvNiUNok9YKsUc7u5nceE/E762oGb1r1RAjlV+KvvPyIlqQXiWtPyNTamtnW9DsVn9PvMttqGWhUoTPxiKhW02TpTnJgWmAIsppd66CnWDolKMBG5GHMPhQJx+z2QtYwexuClmRFy7uBTeTGf4LZfGgMHDCEAU6pIvoGOfzNwcHlpaJZQLAlUbIhqh8/UXvb3K97CCPZXIQe9s7pYKCjeagjBhGQQjuBJ4ll/zo0QOSfH1cro9ZvkX5TMTy2SlkUs7ZgmNEuQFa/6B5lP8RJqXvEVnLimZE6IRT8b/gzZsFgZsJqMxBsVTONLxsMQJoncQWlQzQ3Dty6xwb2u1jR3bhp1iPsVKkCWrYiAy7QfF12h579dDZM0harss12j1x4dosPX0XVWeWR3S422xwpLbfqCwEB4tnUAJZENFvCkEjUvtjW1Rd8eaKQHYbP74rgbhLnNFlfv6TNk2V5hfO0K0LcZ6J+sn8jSLTyqn6EULdNqDERgydJKkze7SghaFOCpVnyNbZ8CNf5+HLR7xJ9OFvVPDWHFH6h5Gbh6f0udx4NDa0Mbq0x78/vgpMssmb2UuQDbxDmpmi/SCKPpTYYcKUsxucNvBosuUJA==
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secrets
      namespace: searxng
    type: Opaque
