loki:
  deploymentMode: SingleBinary

  loki:
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info

  singleBinary:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    readinessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5
    persistence:
      enabled: true
      size: 10Gi

  # Ensure all other deployment modes have 0 replicas
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  ingester:
    replicas: 0

  # Gateway configuration
  gateway:
    enabled: true
    replicas: 1
    basicAuth:
      enabled: false

  # Disable clustering services
  memberlist:
    service:
      enabled: false

  headlessService:
    enabled: false

  # Enterprise features
  enterprise:
    enabled: false

  # Canary
  lokiCanary:
    enabled: false

  test:
    enabled: false

  # RBAC
  rbac:
    pspEnabled: false
    sccEnabled: false
    namespaced: true

  serviceAccount:
    create: true
    automountServiceAccountToken: true