loki:
  deploymentMode: SingleBinary

  loki:
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1
    # Proper schema configuration
    schemaConfig:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    # Storage configuration
    storage:
      type: 'filesystem'
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    # Rate limiting
    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      per_stream_rate_limit: 3MB
      per_stream_rate_limit_burst: 15MB
      max_streams_per_user: 10000
      max_line_size: 256KB
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    # Disable memberlist clustering
    memberlist:
      join_members: []
    # Configure ingester for single binary
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    # Compactor configuration with delete request store
    compactor:
      working_directory: /var/loki/compactor
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      delete_request_store: filesystem  # Required when retention is enabled
    # Configure storage for delete requests
    storage_config:
      filesystem:
        directory: /var/loki/chunks
      # Configure delete request store
      delete_store:
        store: filesystem
        filesystem:
          directory: /var/loki/delete-requests

  singleBinary:
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    readinessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 60
      periodSeconds: 15
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 6
    livenessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 120
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5
    persistence:
      enabled: true
      size: 10Gi

  # Ensure all other deployment modes have 0 replicas
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  ingester:
    replicas: 0

  # Gateway configuration
  gateway:
    enabled: true
    replicas: 1
    basicAuth:
      enabled: false

  # Disable clustering services
  memberlist:
    service:
      enabled: false

  headlessService:
    enabled: false

  # Enterprise features
  enterprise:
    enabled: false

  # Canary
  lokiCanary:
    enabled: false

  test:
    enabled: false

  # RBAC
  rbac:
    pspEnabled: false
    sccEnabled: false
    namespaced: true

  serviceAccount:
    create: true
    automountServiceAccountToken: true