loki:
  deploymentMode: SingleBinary

  loki:
    auth_enabled: false  # Disable auth for simplicity
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info
      # Add server timeout settings
      http_server_read_timeout: 30s
      http_server_write_timeout: 30s
    limits_config:
      # Limit ingestion rate to prevent overwhelming Loki
      ingestion_rate_mb: 10              # Limit to 10MB/min per stream
      ingestion_burst_size_mb: 20        # Allow bursts up to 20MB
      max_streams_per_user: 10000        # Limit number of streams
      max_line_size: 256KB               # Limit log line size
      # Retention settings
      retention_period: 168h             # Keep logs for 7 days
      # Query limits
      max_query_length: 12h              # Limit query time range
      max_query_parallelism: 32          # Limit concurrent queries
      # Split queries to reduce memory usage
      split_queries_by_interval: 15m
    commonConfig:
      path_prefix: /var/loki
      replication_factor: 1  # Single binary only needs replication factor of 1
    storage:
      type: 'filesystem'
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
    # Add schema config to optimize storage
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    useTestSchema: false  # Disable test schema, use proper schema

  singleBinary:
    replicas: 1
    resources:
      requests:
        cpu: 200m       # Increased CPU request
        memory: 256Mi   # Keep request reasonable
      limits:
        cpu: 1000m      # Significantly increased CPU limit
        memory: 1Gi     # Significantly increased memory limit
    # Configure readiness probe with longer delays
    readinessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 45  # Longer initial delay
      periodSeconds: 10
      timeoutSeconds: 10       # Longer timeout
      successThreshold: 1
      failureThreshold: 6
    # Configure liveness probe to be less aggressive
    livenessProbe:
      httpGet:
        path: /ready
        port: 3100
      initialDelaySeconds: 90  # Much longer initial delay
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5      # Allow more failures before restart
    persistence:
      enabled: true
      size: 10Gi      # Increased storage size

  # Ensure all other deployment modes have 0 replicas
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  ingester:
    replicas: 0

  # Enable gateway for routing
  gateway:
    enabled: true
    replicas: 1
    basicAuth:
      enabled: false  # Disable auth for simplicity

  # Disable memberlist service explicitly
  memberlist:
    service:
      enabled: false

  # Enable headless service
  headlessService:
    enabled: true

  # Disable enterprise features
  enterprise:
    enabled: false

  # Disable canary for simplicity
  lokiCanary:
    enabled: false

  test:
    enabled: false

  # Configure RBAC to be namespaced only
  rbac:
    pspEnabled: false
    sccEnabled: false
    namespaced: true  # Use only namespace-scoped RBAC resources

  serviceAccount:
    create: true
    automountServiceAccountToken: true

