apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  containers:
  - args:
    - nvidia-smi
    image: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    name: gpu-test
  tolerations:
  - key: "node-role.kubernetes.io/gpu"
    operator: "Exists"
  nodeSelector:
    nvidia.com/vgpu.present: "true"

