apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-router-metrics
  namespace: vllm
  labels:
    prometheus: prometheus
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      environment: router
      release: router
  namespaceSelector:
    matchNames:
      - vllm
  endpoints:
    - port: router-sport
      interval: 15s
      path: /metrics
