---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-s3-backup-credentials
  namespace: openwebui
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAEWts1Wcz2/LFbR+DVB7saG2a2IBuBMkDh9OY+MblHSU5lbv8aq3eHNnO9TLyV9KfHLGVnXQOS9oM8cIxk7yJSb/crHdfEWCd/SdBGoRzuGWX8xdycAOvYO0+Q1KlegVXIJ6zfFynQwuEP/0hcuXdD4maltU0txEeKorwOAqit+bB/2D71/1aF71QaDJmXQMqNHSEB9n5kZJHwrY6jUDkQRTZB99b0pFNb1iVI75p4U7Toht/FIcsS4I2hvqNhSz92t3h4ftR3uGzjipRn24ZBEcDdk3LSKBnRd+Rb5pZ5/1Yfav6daEOR5O5o1DMos10t+imYiDGj9aq7Kskeh/8ajcTtpGHt21ZrCes705Hh//FpmBYjm/Lj0VVe8qrpG5GXuq8TiTVwirVq1O+MonbguqFM40ZeN6RP3bXe5Pdm6dCik57GMRzuHqyAC9+5e3txR2440aKc/bMCyfuyw0dmOfXH9R/Qp3AoQBhSW/1w3ePGuMqFZeV7aAUb6XGEwlv7nzRnHMwcrYMv7Pjp89T59L9B3aTP1wXU1eEV1GGbBokNvZL5RBK1Tf7E0QQmvQJ6TxcqTmagGsSK5ntoUKIHyIK9PQyeNfKKhVCG2pdcX1uou9bspwOGISQqUu0ztJV4taPNcVpkC7M7QxfFwsbqeJRcPw97h8KG6LRYIXIcdljMNey0XKAqa4xMDpNVvr5i+6K8SwKrDOnqM5CSqrBcDwzggw==
    ACCESS_SECRET_KEY: AgAJ+dOkTHjg61ISUkjlPUO5L2fxjX9BgIEPXzyBFA7BVAtpDvdaQbipxew/9kZ2PNPaP5B715kT9K+9bfmkmXGxszu93SeDqnHL7T5EL2HvJGIOvU9yVH8iIQhCY5ko7qWvFEaWuIa00hbdb0Nm031svRUnJc4Y6jnMSFkCR4gTJzSTGiUDDQGxuLDdLVxcytxVwHo547B124hXhlRb2K7nnusMxFcHMfr1wJwboeFz1OMVk72XdaA4tUVEqmRsQYHWIZfi6xjRhK0dQn1xHUKireBjioCvFr7Ie7kAbEjdAsF0VmuaMHTBrGAsS8o8MTLg97yHK06qNgXFFaQPDbXfQxoi2pcn7HJs1NTo2/Y5Y8r5/2OiAvZ4GuZES6y6tbSzT/BXNrWmdyqxNp5jbzRSsi/WZzAJ9eGs/gXJOE0Pn3MV8UfZe01iR8NedYlJW/sl1dIUU6YFJuo9pk3ndRSGmZg73AQkoU7StVgOdqFCHNVuB47+BS5es1NIhasB0ZhgF+WOiTGFgU7d6wEFrzijnK6fXEcSZHcbDsLdMxhcSsr21RWiHk5U6+fAH0HBl/O4Paogs6Qq19ndReA13IBbLyj4WNSlHWzrylbf+x9XgJEiUVIMkOdldFsW8PujsTn4Wc8aPIwqS++OEKyexP1uziAC01Y8R+2xZM0GvaMUnkwd4BYm3mtiSJ2B1V5QembMOefoUhpHxw/Nps1jpMVrz5uzdhnvDSIplvuldgKn5vj6Xs/Dt30H
  template:
    metadata:
      creationTimestamp: null
      name: hetzner-s3-backup-credentials
      namespace: openwebui
    type: Opaque
