---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-litellm
  namespace: openwebui
spec:
  encryptedData:
    password: AgAFE1YbWQGsI7nzZib1QaE1M8RIQJSbRNllvBgimflWCSUu3CTPDB2AgCHtRcSFQ/UHQOR+oZ2vFew0NKR3YrwalTHJ6Do+rrQC9KqmJ9Rr0Om+KlfHP0UhPKxeDWk2+cjURZZzek6DtuvlsbXdlRG3aMdT4q0RLXhvaq6Qa7HDudtqT47swCGzEeyaK8SvZJUHVYJ/aBUWm5os3ZGE/7Uf5lmBykoSCAjVKKkpPqK2YusZiZQd4Rm2pn6Hqdz+40IeULa3CvFan84cq3GnULN0KvZ3Kw28ZLduRDbWoqbrbgo5aGkwatn4VNKKB30o9wqeF+Q/3EpGSJguNWye9zrb+1KqZl80a8AxelnQLLxxZgVBFLEVE3pvmkHroUGgXUF7nngw36Mb6r4BmqyBcQKA+6Ntfn0oUSsO7XeUfW7pMGRA33EXoZB+oidzHI/hyD6YpNoFOO3wpANBTh5VbjMZ/ULNaaMpfSp3Tnt6I2jCUJzBJE6Uf9rN2nU2nx+I0B8XjzPddOBJdsyHfDQPSD3ZjEg/TldxJ/Vn41iLQqYfF39uOJzUmwaQzkYrT4D5sC/7KTtrvKxhek1U48LskVcwLop8mKqAoGF5RLC4ne+E90mAg7NUOYuOdwUC+/6DKuN17xHvgqvhnr6+b1T9g4RjY8hrMdxkKM9KB7om8jC8oORv2H03COJNqar4+aoR45mPWwatWONFjyv17cXIF8XCZRZKIxVEt5J0VrdLiiZBgg==
    username: AgCaOD+fSy+Vz2xGSsTANUPBJu5W8nSUB3iNv1tZWwgpAGH+CsMxdUQx5t1LXvccJ6iogBTgUryfrAX7os74CvywV76GRV66k01JaxPSvVLQd5yNZOhWmj110XCWuRHi5y1FJG6f1ptRdO+aiH4zHjihlAWO55xFmze91H61wSg3aRpOkBf1NScxoyiILYp241Ri4ZB1kn7S1RyiJWZkhngh6HMZf9aNq2oJ3KT9UiYooI4TC1G4maINM0nzw5VO5Pq9qbDL0JWSIIkdwf+EM+PWqQkucbfOmFqnOLV5UsFKp08YEO4CBnTX/Ejyyx+HlUs+h6SOagVA5pKLLUoRac+SzYOJlU19bceu85FzQO9yk7Z7WgGC2O9EqRUfq3GgmPLLsXC6U+0pltNkl4q610dFZeKRKHJXDrr3EjLZPyYsibJCVepNMsiauSDCNJY7UC904iMwDkfaGA/KsR5wjwTTLPYGxOaxDSsIsmMDH3SHaQjIcIuTzFA9+ows0AZ6SXG6+FEB93gg4EIWR5G3Uy+ABQ4wOIkowxs52BVRbIH2Mppl/1Pr9Ibzpr1nM5wmt6JJFnbMPof99Em4g622lRjI2qq1wz/SjV+GuvTjbbDmzMQ/tmfSu7fWFmrg9Qcpx8ZSqE8nBp1GErgqZGwnFScgb+k5LD9Lzz+rWRpSa0b6Urd5OZcXChfB+8PU5ENJbJBos2Plk5do3tM=
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-litellm
      namespace: openwebui
    type: Opaque
